FROM mesosphere/mesos-slave:0.28.0-2.0.16.ubuntu1404
MAINTAINER Christian Decker <decker.christian@gmail.com>
RUN apt-get update && apt-get install -y docker.io && apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*
